---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "learning-go-chart.fullname" . }}-secrets
type: Opaque
data:
  YOUTUBE_API_KEY: "{{ .Values.learningGoSettings.ytAPIKey | default "" | b64enc}}"
  YOUTUBE_CHANNEL_ID: "{{ .Values.learningGoSettings.ytChannelID | default "" | b64enc}}"